language: java

dist: jammy

jdk: openjdk17

services:
  - mysql

before_install:
  - chmod +x mvnw
  - mysql -e "CREATE USER jbelly@'%' IDENTIFIED BY 'jbelly';"
  - mysql -e "CREATE DATABASE jbelly CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;"
  - mysql -e "GRANT ALL PRIVILEGES ON jbelly.* TO jbelly@'%';"
  - mysql -e "FLUSH PRIVILEGES;"
