version: '{build}'

environment:
  JAVA_HOME: C:\Program Files\Java\jdk11
  MYSQL_PATH: C:\Program Files\MySQL\MySQL Server 5.7
  MYSQL_PWD: Password12!

services:
  - mysql

init:
  - SET PATH=%JAVA_HOME%\bin;%MYSQL_PATH%\bin;%PATH%
  - javac -version
  - mvn --version

before_build:
  - mysql -e "CREATE DATABASE jbelly CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" --user=root --password=Password12!
  - mysql --database=mysql -e "update user set authentication_string=PASSWORD("") where User='root';" --user=root --password=Password12!
  - mysql -e "flush privileges;" --user=root --password=

build_script:
  - mvn clean package --batch-mode -DskipTest

test_script:
  - mvn clean install --batch-mode