version: '{build}'

environment:
  JAVA_HOME: C:\Program Files\Java\jdk11
  MYSQL_PWD: Password12!

services:
  - mysql

init:
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - echo %PATH%
  - javac -version
  - mvn --version

install:
  - mysql -e "CREATE DATABASE jbelly CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" -uroot

build_script:
  - mvn clean package --batch-mode -DskipTest

test_script:
  - mvn clean install --batch-mode