version: '{build}'

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk11

install:
  - java -version
  - mvn --version

build_script:
  - mvn clean package --batch-mode -DskipTest

test_script:
  - mvn clean install --batch-mode