image:
  Visual Studio 2022

version:
  '{build}'

environment:
  JAVA_HOME: C:\Program Files\Java\jdk17
  MYSQL_PATH: C:\Program Files\MySQL\MySQL Server 8.0
  MYSQL_PWD: Password12!

services:
  - mysql

init:
  - ps: Start-Service MySQL80
  - SET PATH=%JAVA_HOME%\bin;%MYSQL_PATH%\bin;%PATH%
  - javac -version
  - mvn --version

before_build:
  - mysql -e "CREATE USER jbelly@'%' IDENTIFIED BY 'jbelly';" -u root
  - mysql -e "CREATE DATABASE jbelly CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" -u root
  - mysql -e "GRANT ALL PRIVILEGES ON jbelly.* TO jbelly@'%';" -u root
  - mysql -e "FLUSH PRIVILEGES;" -u root

build_script:
  - ./mvnw install --batch-mode --show-version

test_script:
  - ./mvnw test --batch-mode --show-version
