version: '{build}'

environment:
  MYSQL_PATH: C:\Program Files\MySql\MySQL Server 5.7
  MYSQL_PWD: Password12!
  JAVA_HOME: C:\Program Files\Java\jdk11

services:
  - mysql

init:
  - SET PATH=%JAVA_HOME%\bin;%MYSQL_PATH%\bin;%PATH%
  - javac -version
  - mvn --version

install:
  - mysql -e "CREATE DATABASE jbelly CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" --user=root

build_script:
  - mvn clean package --batch-mode -DskipTest

test_script:
  - mvn clean install --batch-mode