services:
   db:
     image: mysql:8.0
     volumes:
      - /opt/jbelly_docker_data/db/mysql:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: jbelly
       MYSQL_DATABASE: jbelly
       MYSQL_USER: jbelly
       MYSQL_PASSWORD: jbelly
     command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_0900_ai_ci", "--skip-character-set-client-handshake"]

   app:
     depends_on:
       - db
     image: evgeniyosipov/jbelly:latest
     ports:
       - "8080:8080"
     environment:
       JBELLY_MYSQL_HOST: db
       JBELLY_MYSQL_PORT: 3306
     command: bash -c "
       git pull
       && ./mvnw spring-boot:run
       "
